version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: dbms_mini_project
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dikshith@06
      POSTGRES_DB: dbms_mini_2
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: ./next-app
    container_name: next_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dikshith@06
      POSTGRES_DB: dbms_mini_2

volumes:
  pgdata:
