version: "3.8"

services:
  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0605
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=dbms_mini_2
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0605
      POSTGRES_DB: dbms_mini_2
    ports:
      - "5433:5432" # Expose container's 5432 as host's 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
